### ISSUE TITLE
Can't save to ODS format.

### ISSUE THREAD

**Issue by Geohexamon** [SheetJS/sheetjs#2121]
Whenever I attempt to save to an ODS format I am met with the following error. 

```
/rbd/pnpm-volume/278dbf49-afd7-493e-9052-fd5046a86522/node_modules/.registry.npmjs.org/xlsx/0.16.7/node_modules/xlsx/xlsx.js:3685
	var idx = range.indexOf(":");
	                ^
TypeError: Cannot read property 'indexOf' of undefined
    at decode_range (/rbd/pnpm-volume/278dbf49-afd7-493e-9052-fd5046a86522/node_modules/.registry.npmjs.org/xlsx/0.16.7/node_modules/xlsx/xlsx.js:3685:18)
    at write_ws (/rbd/pnpm-volume/278dbf49-afd7-493e-9052-fd5046a86522/node_modules/.registry.npmjs.org/xlsx/0.16.7/node_modules/xlsx/xlsx.js:20281:24)
    at wcx (/rbd/pnpm-volume/278dbf49-afd7-493e-9052-fd5046a86522/node_modules/.registry.npmjs.org/xlsx/0.16.7/node_modules/xlsx/xlsx.js:20427:57)
    at write_ods (/rbd/pnpm-volume/278dbf49-afd7-493e-9052-fd5046a86522/node_modules/.registry.npmjs.org/xlsx/0.16.7/node_modules/xlsx/xlsx.js:20451:23)
    at write_zip (/rbd/pnpm-volume/278dbf49-afd7-493e-9052-fd5046a86522/node_modules/.registry.npmjs.org/xlsx/0.16.7/node_modules/xlsx/xlsx.js:20798:36)
    at write_zip_type (/rbd/pnpm-volume/278dbf49-afd7-493e-9052-fd5046a86522/node_modules/.registry.npmjs.org/xlsx/0.16.7/node_modules/xlsx/xlsx.js:21041:10)
    at writeSync (/rbd/pnpm-volume/278dbf49-afd7-493e-9052-fd5046a86522/node_modules/.registry.npmjs.org/xlsx/0.16.7/node_modules/xlsx/xlsx.js:21145:22)
    at Object.writeFileSync (/rbd/pnpm-volume/278dbf49-afd7-493e-9052-fd5046a86522/node_modules/.registry.npmjs.org/xlsx/0.16.7/node_modules/xlsx/xlsx.js:21168:9)
```

For context. I can save to xlsx format with zero issues. I'm editing a source ODS file and saving it out as a seperate file.

**Comment by SheetJSDev** [comment]
Can you share the original file?  If I had to guess, there's an empty worksheet without a range

**Comment by Geohexamon** [comment]
Here are both of the ODS files that I used for testing. Both spat out the error and both do have empty sheets in them.

[ODS files I used to test with.zip](https://github.com/SheetJS/sheetjs/files/5324165/ODS.files.I.used.to.test.with.zip)

**Comment by SheetJSDev** [comment]
The other file has an empty Options worksheet, which is being parsed as an empty object without a `!ref` key.  The fix is to force it to report a range of "A1:A1" when no cells are encountered.  Feel free to send a PR changing `bits/80_parseods.js` as follows:

```diff
diff --git a/bits/80_parseods.js b/bits/80_parseods.js
index f8d81ab..7715a6e 100644
--- a/bits/80_parseods.js
+++ b/bits/80_parseods.js
@@ -64,6 +64,7 @@ var parse_content_xml = (function() {
                        case 'table': case '工作表': // 9.1.2 <table:table>
                                if(Rn[1]==='/') {
                                        if(range.e.c >= range.s.c && range.e.r >= range.s.r) ws['!ref'] = encode_range(range);
+                                       else ws['!ref'] = "A1:A1";
                                        if(opts.sheetRows > 0 && opts.sheetRows <= range.e.r) {
                                                ws['!fullref'] = ws['!ref'];
                                                range.e.r = opts.sheetRows - 1;
```

**Comment by SheetJSDev** [comment]
Thanks, we'll try to roll out a release today
