### ISSUE TITLE
Corrupted zip : can't find end of central directory

### ISSUE THREAD

**Issue by mohitsisodiya09** [SheetJS/sheetjs#2204]
After Downloading an excel file(xlsx), given a path of the downloaded file for reading and converting XLSX to JSON, 
but while reading the file:  var workbook = await xlsx.readFile(path);
the following error is coming.

Error: Corrupted zip : can't find end of central directory
    at ZipEntries.readEndOfCentral ({folderName}/xlsx/jszip.js:2282:19)
    at ZipEntries.load ({folderName}/xlsx/jszip.js:2344:14)
    at new ZipEntries ({folderName}/xlsx/jszip.js:2168:14)
    at JSZipSync.module.exports [as load] ({folderName}/xlsx/jszip.js:581:18)
    at new JSZipSync ({folderName}/xlsx/jszip.js:528:14)
    at zip_read ({folderName}/xlsx/xlsx.js:2973:24)
    at read_zip ({folderName}/xlsx/xlsx.js:20924:8)
    at readSync ({folderName}/xlsx/xlsx.js:20991:69)
    at Object.readFileSync ({folderName}/xlsx/xlsx.js:21005:9)
    at IncomingMessage.emit (events.js:333:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by SheetJSDev** [comment]
That error suggests the file may not be a valid XLSX file.  Can you confirm the file can be loaded in Excel and the actual path points to the correct file?

**Comment by MohitSisodiya** [comment]
Yes, I verified the .xlsx file it's opening in Excel and Path is also correct.

**Comment by kennydifiore** [comment]
Seeing similar issues with XLSX files created with the sheetjs library on Android 10 in a React Native environment:
```
Archive:  Export Schedule w_o Allow List Assessments-5.xlsx
warning [Export Schedule w_o Allow List Assessments-5.xlsx]:  208 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [Export Schedule w_o Allow List Assessments-5.xlsx]:  reported length of central directory is
  -208 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
  zipfile?).  Compensating...
 extracting: docProps/core.xml       
 extracting: docProps/app.xml        
 extracting: xl/worksheets/sheet1.xml  
 extracting: xl/workbook.xml         
 extracting: xl/theme/theme1.xml     
 extracting: xl/styles.xml           
 extracting: [Content_Types].xml     
 extracting: _rels/.rels             
 extracting: xl/_rels/workbook.xml.rels  
```
