### ISSUE TITLE
SyntaxError: Invalid regular expression: /+$/: Nothing to repeat

### ISSUE THREAD

**Issue by jnachtigall** [SheetJS/sheetjs#2258]
Using `xlsx` on my laptop (windows 10, node version 14) as command line program works fine. However, on our gitlab CI I get the following error (linux, both with node 10 and node 14):

```
> xlsx --file=src/data/excel/Uebersicht-Projekte-in-Bayern-2021-02-10.xlsx --field-sep=; --output=src/data/excel/csvtojson-artifact/Uebersicht-Projekte-in-Bayern.csv
Uebersicht-Projekte-in-Bayern-2
/builds/baystmd/mma/mobility-map-app/node_modules/xlsx/xlsx.js:21580
		var endregex = new RegExp((FS=="|" ? "\\|" : FS)+"+$");
		               ^
SyntaxError: Invalid regular expression: /+$/: Nothing to repeat
    at new RegExp (<anonymous>)
    at Object.write_csv_stream [as to_csv] (/builds/baystmd/mma/mobility-map-app/node_modules/xlsx/xlsx.js:21580:18)
    at Object.<anonymous> (/builds/baystmd/mma/mobility-map-app/node_modules/xlsx/bin/xlsx.njs:258:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by SheetJSDev** [comment]
In bash and other shells, `;` denotes end of statement.  So it's being parsed like two commands, the first of which is 

```bash
xlsx --file=src/data/excel/Uebersicht-Projekte-in-Bayern-2021-02-10.xlsx --field-sep=
```

To pass a literal semicolon, wrap in double quotes:

```js
xlsx --file=src/data/excel/Uebersicht-Projekte-in-Bayern-2021-02-10.xlsx --field-sep=";" --output=src/data/excel/csvtojson-artifact/Uebersicht-Projekte-in-Bayern.csv Uebersicht-Projekte-in-Bayern-2
```

We would accept a PR that uses a default field separator.  In `bin/xlsx.njs`:

```diff
@@ -256,7 +256,7 @@ switch(true) {
 
        default:
                if(!program.book) {
-                       var stream = X.stream.to_csv(ws, {FS:program.fieldSep, RS:program.rowSep});
+                       var stream = X.stream.to_csv(ws, {FS:program.fieldSep||",", RS:program.rowSep||"\n"});
                        if(program.output) stream.pipe(fs.createWriteStream(program.output));
                        else stream.pipe(process.stdout);
                } else doit(function(ws) { return X.utils.sheet_to_csv(ws,{FS:program.fieldSep, RS:program.rowSep}); });
```
