### ISSUE TITLE
workbook.Sheets is not a function

### ISSUE THREAD

**Issue by cong1999** [SheetJS/sheetjs#2437]
var ws = workbook.Sheets('Sheet1')
                  ^

TypeError: workbook.Sheets is not a function
    at Object.<anonymous> (C:\Users\CongWang\Desktop\finance\v1\app\finance\test\test.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by cong1999** [comment]
var xlsx = require('xlsx')

var workbook = xlsx.readFile('test.xlsx', {cellDates: true})
var ws = workbook.Sheets('Sheet1')

var data =  xlsx.utils.sheet_to_json(ws)

console.log(data)

**Comment by reviewher** [comment]
`workbook.Sheets` is an array, you should use

```js
var ws = workbook.Sheets['Sheet1'];
```

**Comment by cong1999** [comment]
Think  you!! @reviewher
