### ISSUE TITLE
sheet_to_row_object_array(sheet) crashes when looping through sheetnames

### ISSUE THREAD

**Issue by artiee** [SheetJS/sheetjs#4]
The following code crashes

``` javascript
var XLSX = require('xlsx')
var xlsx = XLSX.readFile('test.xlsx')

xlsx.SheetNames.forEach(function(sheetName) {

  // this works if sheetname is given:
  // var parsedSheet = XLSX.utils.sheet_to_row_object_array(xlsx.Sheets["3AU"])

// this crashes:
  var parsedSheet = XLSX.utils.sheet_to_row_object_array(xlsx.Sheets[sheetName])

  console.log(parsedSheet)

})
```

C:\IS\node\node_modules\xlsx\xlsx.js:338
        if (sheet["!ref"]) {
                 ^
TypeError: Cannot read property '!ref' of undefined
    at Object.sheet_to_row_object_array (C:\IS\node\node_modules\xlsx\xlsx.js:338:11)
    at C:\IS\node\testapp\app3.js:9:32
    at Array.forEach (native)
    at Object.<anonymous> (C:\IS\node\testapp\app3.js:5:17)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by chethan-K** [comment]
Hi  @Niggler 

Does sheet_to_row_object_array ensures the running order of excel sheet rows...?

Thanks in advance

**Comment by SheetJSDev** [comment]
@chethan-K I think you are asking if the rows are in the same order that they appear in the excel sheet, and the answer is yes (it walks row-by-row in order when generating the output)

**Comment by chethan-K** [comment]
@SheetJSDev Yes, I was looking for the same thing. Thanks :)
